export const officeSpaceTypes = [
    'Private Office',
    'Shared Office',
    'Open Office',
    'Co-working Space',
    'Meeting Room',
    'Conference Room',
    'Boardroom',
    'Virtual Office',
    'Hot Desk',
    'Executive Suite',
    'Training Room',
    'Lounge Area',
    'Cafeteria',
    'Business Center',
    'Incubator Space',
    'Flex Space',
    'Startup Hub',
    'Food Store',
    'Electronic Hardware Store',
    'Shop',
    'Warehouse',
    'Multi-purpose store',
    'Classroom complex'
];